package QoS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAvailability = createDescriptorForAvailability();
  /*package*/ final ConceptDescriptor myConceptCapabilitiesProfile = createDescriptorForCapabilitiesProfile();
  /*package*/ final ConceptDescriptor myConceptCapability = createDescriptorForCapability();
  /*package*/ final ConceptDescriptor myConceptDataRate = createDescriptorForDataRate();
  /*package*/ final ConceptDescriptor myConceptDeadline = createDescriptorForDeadline();
  /*package*/ final ConceptDescriptor myConceptDelay = createDescriptorForDelay();
  /*package*/ final ConceptDescriptor myConceptDepth = createDescriptorForDepth();
  /*package*/ final ConceptDescriptor myConceptDurability = createDescriptorForDurability();
  /*package*/ final ConceptDescriptor myConceptErrorRate = createDescriptorForErrorRate();
  /*package*/ final ConceptDescriptor myConceptHistory = createDescriptorForHistory();
  /*package*/ final ConceptDescriptor myConceptJitter = createDescriptorForJitter();
  /*package*/ final ConceptDescriptor myConceptLeaseDuration = createDescriptorForLeaseDuration();
  /*package*/ final ConceptDescriptor myConceptLifespan = createDescriptorForLifespan();
  /*package*/ final ConceptDescriptor myConceptLiveliness = createDescriptorForLiveliness();
  /*package*/ final ConceptDescriptor myConceptLossRate = createDescriptorForLossRate();
  /*package*/ final ConceptDescriptor myConceptQoSDefinition = createDescriptorForQoSDefinition();
  /*package*/ final ConceptDescriptor myConceptReliability = createDescriptorForReliability();
  /*package*/ final ConceptDescriptor myConceptRequirement = createDescriptorForRequirement();
  /*package*/ final ConceptDescriptor myConceptRequirementsProfile = createDescriptorForRequirementsProfile();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAvailability, myConceptCapabilitiesProfile, myConceptCapability, myConceptDataRate, myConceptDeadline, myConceptDelay, myConceptDepth, myConceptDurability, myConceptErrorRate, myConceptHistory, myConceptJitter, myConceptLeaseDuration, myConceptLifespan, myConceptLiveliness, myConceptLossRate, myConceptQoSDefinition, myConceptReliability, myConceptRequirement, myConceptRequirementsProfile);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Availability:
        return myConceptAvailability;
      case LanguageConceptSwitch.CapabilitiesProfile:
        return myConceptCapabilitiesProfile;
      case LanguageConceptSwitch.Capability:
        return myConceptCapability;
      case LanguageConceptSwitch.DataRate:
        return myConceptDataRate;
      case LanguageConceptSwitch.Deadline:
        return myConceptDeadline;
      case LanguageConceptSwitch.Delay:
        return myConceptDelay;
      case LanguageConceptSwitch.Depth:
        return myConceptDepth;
      case LanguageConceptSwitch.Durability:
        return myConceptDurability;
      case LanguageConceptSwitch.ErrorRate:
        return myConceptErrorRate;
      case LanguageConceptSwitch.History:
        return myConceptHistory;
      case LanguageConceptSwitch.Jitter:
        return myConceptJitter;
      case LanguageConceptSwitch.LeaseDuration:
        return myConceptLeaseDuration;
      case LanguageConceptSwitch.Lifespan:
        return myConceptLifespan;
      case LanguageConceptSwitch.Liveliness:
        return myConceptLiveliness;
      case LanguageConceptSwitch.LossRate:
        return myConceptLossRate;
      case LanguageConceptSwitch.QoSDefinition:
        return myConceptQoSDefinition;
      case LanguageConceptSwitch.Reliability:
        return myConceptReliability;
      case LanguageConceptSwitch.Requirement:
        return myConceptRequirement;
      case LanguageConceptSwitch.RequirementsProfile:
        return myConceptRequirementsProfile;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAvailability() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Availability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba270L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613744");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCapabilitiesProfile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "CapabilitiesProfile", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d14L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8489988947995225364");
    b.version(2);
    b.aggregate("policies", 0x75d27ff7603f6d21L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(true).origin("8489988947995225377").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCapability() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.class_(false, true, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8489988947995225367");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataRate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "DataRate", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26dL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613741");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDeadline() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Deadline", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba267L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613735");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDelay() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Delay", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26cL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613740");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDepth() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Depth", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba264L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613732");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDurability() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Durability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba266L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613734");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForErrorRate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "ErrorRate", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26fL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613743");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHistory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "History", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba263L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613731");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJitter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Jitter", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26bL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613739");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLeaseDuration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "LeaseDuration", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26aL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613738");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLifespan() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Lifespan", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba268L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613736");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLiveliness() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Liveliness", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba269L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613737");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLossRate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "LossRate", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26eL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613742");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQoSDefinition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "QoSDefinition", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x57f420665365fe0L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/396107887467192288");
    b.version(2);
    b.aggregate("capabilities", 0x57f420665365fe3L).target(0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d14L).optional(true).ordered(true).multiple(true).origin("396107887467192291").done();
    b.aggregate("requirements", 0xdbe2d924f785bbfL).target(0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0xdbe2d924f785bbaL).optional(true).ordered(true).multiple(true).origin("990279074489850815").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReliability() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Reliability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba265L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Capability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d17L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/8011641641332613733");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequirement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "Requirement", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x4bc2f2a09e3d0ef1L);
    b.class_(false, true, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/5459192469989953265");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequirementsProfile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QoS", "RequirementsProfile", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0xdbe2d924f785bbaL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ca64c7cd-6639-4b1e-85dc-28366b5a0c63(QoS.structure)/990279074489850810");
    b.version(2);
    b.aggregate("requirements", 0x155e900c12933412L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(true).origin("1539826504132932626").done();
    return b.create();
  }
}
